/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetjava;
import javax.swing.*;

/**
 *
 * @author HP
 */
public class Homer extends javax.swing.JFrame {

    /**
     * Creates new form Homer
     */
    public Homer(String nom_responsable) {
        initComponents();
        setUsers(nom_responsable);
    }
Homer() {
      throw new UnsupportedOperationException("Not supported yet.");  //To change body of generated methods, choose Tools | Templates.
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        utilisateurr = new javax.swing.JLabel();
        LogoutBtnr = new javax.swing.JButton();
        Statistiquer = new javax.swing.JButton();
        Statistiquemr = new javax.swing.JButton();
        ajoutu = new javax.swing.JButton();
        ajoutr = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 255));
        jLabel1.setText("GCOLIS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, -1, -1));

        utilisateurr.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        utilisateurr.setForeground(new java.awt.Color(0, 204, 204));
        utilisateurr.setText("MENU");
        getContentPane().add(utilisateurr, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, -1, -1));

        LogoutBtnr.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        LogoutBtnr.setForeground(new java.awt.Color(0, 153, 153));
        LogoutBtnr.setText("Logout");
        LogoutBtnr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutBtnrActionPerformed(evt);
            }
        });
        getContentPane().add(LogoutBtnr, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 610, 341, 50));

        Statistiquer.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Statistiquer.setForeground(new java.awt.Color(0, 153, 153));
        Statistiquer.setText("Statististiques Annuelles");
        Statistiquer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StatistiquerActionPerformed(evt);
            }
        });
        getContentPane().add(Statistiquer, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 460, 341, 54));

        Statistiquemr.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Statistiquemr.setForeground(new java.awt.Color(0, 153, 153));
        Statistiquemr.setText("Statististiques Monsuelles");
        Statistiquemr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StatistiquemrActionPerformed(evt);
            }
        });
        getContentPane().add(Statistiquemr, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 534, -1, 60));

        ajoutu.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        ajoutu.setForeground(new java.awt.Color(0, 153, 153));
        ajoutu.setText("Ajouter Utilisateur");
        ajoutu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajoutuActionPerformed(evt);
            }
        });
        getContentPane().add(ajoutu, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, 341, 50));

        ajoutr.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        ajoutr.setForeground(new java.awt.Color(0, 153, 153));
        ajoutr.setText("Ajouter Responsable");
        ajoutr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajoutrActionPerformed(evt);
            }
        });
        getContentPane().add(ajoutr, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 390, 341, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\THIERRY\\Desktop\\Projet MOBILE\\TEMPLATE\\01\\PJAVA\\src\\Icon\\logo_1.png")); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 110, 140));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\THIERRY\\Desktop\\Projet MOBILE\\TEMPLATE\\01\\PJAVA\\src\\Icon\\Kia Seltos_1.jpeg")); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 830));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LogoutBtnrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutBtnrActionPerformed
        Loginr LoginrFrame = new Loginr();
        LoginrFrame.setVisible(true);
        LoginrFrame.pack();
        LoginrFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_LogoutBtnrActionPerformed

    private void StatistiquerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StatistiquerActionPerformed
        // TODO add your handling code here:
        StatistiquesAnnuelles StatistiquesAnnuellesFrame = new StatistiquesAnnuelles();
        StatistiquesAnnuellesFrame.setVisible(true);
        StatistiquesAnnuellesFrame.pack();
        StatistiquesAnnuellesFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_StatistiquerActionPerformed

    private void StatistiquemrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StatistiquemrActionPerformed
        // TODO add your handling code here:
        StatistiquesMensuelles  StatistiquesMensuellesFrame = new StatistiquesMensuelles ();
        StatistiquesMensuellesFrame.setVisible(true);
        StatistiquesMensuellesFrame.pack();
        StatistiquesMensuellesFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_StatistiquemrActionPerformed

    private void ajoutuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajoutuActionPerformed
        // TODO add your handling code here:
        SignUpu SignUpuFrame = new SignUpu();
        SignUpuFrame.setVisible(true);
        SignUpuFrame.pack();
        SignUpuFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_ajoutuActionPerformed

    private void ajoutrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajoutrActionPerformed
        // TODO add your handling code here:
        SignUpr SignUprFrame = new SignUpr();
        SignUprFrame.setVisible(true);
        SignUprFrame.pack();
        SignUprFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_ajoutrActionPerformed

    /**
     * @param args the command line arguments
     */
     public void setUsers(String nom_responsable) {
    utilisateurr.setText(nom_responsable);
}
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Homer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Homer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Homer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Homer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Homer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LogoutBtnr;
    private javax.swing.JButton Statistiquemr;
    private javax.swing.JButton Statistiquer;
    private javax.swing.JButton ajoutr;
    private javax.swing.JButton ajoutu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel utilisateurr;
    // End of variables declaration//GEN-END:variables
}
