/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetjava;
import javax.swing.*;

/**
 *
 * @author HP
 */
public class Home extends javax.swing.JFrame {

   

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

   public Home(String nom_utilisateur) {
        initComponents();
        setUser(nom_utilisateur);//To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        utilisateur = new javax.swing.JLabel();
        LogoutBtn = new javax.swing.JButton();
        Suivantbtn = new javax.swing.JButton();
        Suivantbtn1 = new javax.swing.JButton();
        Suivantbtn2 = new javax.swing.JButton();
        Suivantbtn3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 255));
        jLabel1.setText("Welcome Back");

        utilisateur.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        utilisateur.setForeground(new java.awt.Color(0, 204, 204));
        utilisateur.setText("John");

        LogoutBtn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        LogoutBtn.setForeground(new java.awt.Color(0, 153, 153));
        LogoutBtn.setText("Logout");
        LogoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutBtnActionPerformed(evt);
            }
        });

        Suivantbtn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Suivantbtn.setForeground(new java.awt.Color(0, 153, 153));
        Suivantbtn.setText("Page colis");
        Suivantbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SuivantbtnActionPerformed(evt);
            }
        });

        Suivantbtn1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Suivantbtn1.setForeground(new java.awt.Color(0, 153, 153));
        Suivantbtn1.setText("Page reception");
        Suivantbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Suivantbtn1ActionPerformed(evt);
            }
        });

        Suivantbtn2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Suivantbtn2.setForeground(new java.awt.Color(0, 153, 153));
        Suivantbtn2.setText("Statististiques Annuelles");
        Suivantbtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Suivantbtn2ActionPerformed(evt);
            }
        });

        Suivantbtn3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Suivantbtn3.setForeground(new java.awt.Color(0, 153, 153));
        Suivantbtn3.setText("Statististiques Monsuelles");
        Suivantbtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Suivantbtn3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(utilisateur, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(119, 119, 119))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Suivantbtn1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Suivantbtn)
                        .addGap(39, 39, 39))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Suivantbtn3)
                    .addComponent(Suivantbtn2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(47, 47, 47)
                            .addComponent(jLabel1))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(150, 150, 150)
                            .addComponent(LogoutBtn))))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(utilisateur, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LogoutBtn)
                .addGap(38, 38, 38)
                .addComponent(Suivantbtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Suivantbtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Suivantbtn1)
                    .addComponent(Suivantbtn))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LogoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutBtnActionPerformed
              Login LoginFrame = new Login();
              LoginFrame.setVisible(true);
              LoginFrame.pack();
              LoginFrame.setLocationRelativeTo(null); 
              this.dispose();
    }//GEN-LAST:event_LogoutBtnActionPerformed

    private void SuivantbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SuivantbtnActionPerformed
        // TODO add your handling code here:
        Menu MenuFrame = new Menu();
              MenuFrame.setVisible(true);
              MenuFrame.pack();
              MenuFrame.setLocationRelativeTo(null); 
              this.dispose();
    }//GEN-LAST:event_SuivantbtnActionPerformed

    private void Suivantbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Suivantbtn1ActionPerformed
        // TODO add your handling code here:
        Reception ReceptionFrame = new Reception();
              ReceptionFrame.setVisible(true);
              ReceptionFrame.pack();
              ReceptionFrame.setLocationRelativeTo(null); 
              this.dispose();
    }//GEN-LAST:event_Suivantbtn1ActionPerformed

    private void Suivantbtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Suivantbtn2ActionPerformed
        // TODO add your handling code here:
        StatistiquesAnnuelles StatistiquesAnnuellesFrame = new StatistiquesAnnuelles();
              StatistiquesAnnuellesFrame.setVisible(true);
              StatistiquesAnnuellesFrame.pack();
              StatistiquesAnnuellesFrame.setLocationRelativeTo(null); 
              this.dispose();
    }//GEN-LAST:event_Suivantbtn2ActionPerformed

    private void Suivantbtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Suivantbtn3ActionPerformed
        // TODO add your handling code here:
         StatistiquesMensuelles  StatistiquesMensuellesFrame = new StatistiquesMensuelles ();
              StatistiquesMensuellesFrame.setVisible(true);
              StatistiquesMensuellesFrame.pack();
              StatistiquesMensuellesFrame.setLocationRelativeTo(null); 
              this.dispose();
    }//GEN-LAST:event_Suivantbtn3ActionPerformed
      
    public void setUser(String nom_utilisateur) {
    utilisateur.setText(nom_utilisateur);
}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LogoutBtn;
    private javax.swing.JButton Suivantbtn;
    private javax.swing.JButton Suivantbtn1;
    private javax.swing.JButton Suivantbtn2;
    private javax.swing.JButton Suivantbtn3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel utilisateur;
    // End of variables declaration//GEN-END:variables

}