/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetjava;
import javax.swing.*;

/**
 *
 * @author HP
 */
public class Home extends javax.swing.JFrame {

   

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

   public Home(String nom_utilisateur) {
        initComponents();
        setUser(nom_utilisateur);//To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        utilisateur = new javax.swing.JLabel();
        LogoutBtn = new javax.swing.JButton();
        Suivantbtn = new javax.swing.JButton();
        Suivantbtn1 = new javax.swing.JButton();
        Suivantbtn2 = new javax.swing.JButton();
        Suivantbtn3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 255));
        jLabel1.setText("GCOLIS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, -1, -1));

        utilisateur.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        utilisateur.setForeground(new java.awt.Color(0, 204, 204));
        utilisateur.setText("MENU");
        getContentPane().add(utilisateur, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 270, -1, -1));

        LogoutBtn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        LogoutBtn.setForeground(new java.awt.Color(0, 153, 153));
        LogoutBtn.setText("Logout");
        LogoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutBtnActionPerformed(evt);
            }
        });
        getContentPane().add(LogoutBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 604, 341, 49));

        Suivantbtn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Suivantbtn.setForeground(new java.awt.Color(0, 153, 153));
        Suivantbtn.setText("Page colis");
        Suivantbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SuivantbtnActionPerformed(evt);
            }
        });
        getContentPane().add(Suivantbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 309, 341, 54));

        Suivantbtn1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Suivantbtn1.setForeground(new java.awt.Color(0, 153, 153));
        Suivantbtn1.setText("Page reception");
        Suivantbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Suivantbtn1ActionPerformed(evt);
            }
        });
        getContentPane().add(Suivantbtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 381, 341, 52));

        Suivantbtn2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Suivantbtn2.setForeground(new java.awt.Color(0, 153, 153));
        Suivantbtn2.setText("Statististiques Annuelles");
        Suivantbtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Suivantbtn2ActionPerformed(evt);
            }
        });
        getContentPane().add(Suivantbtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 453, 341, 57));

        Suivantbtn3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Suivantbtn3.setForeground(new java.awt.Color(0, 153, 153));
        Suivantbtn3.setText("Statististiques Monsuelles");
        Suivantbtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Suivantbtn3ActionPerformed(evt);
            }
        });
        getContentPane().add(Suivantbtn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 528, -1, 58));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\THIERRY\\Desktop\\Projet MOBILE\\TEMPLATE\\01\\PJAVA\\src\\Icon\\logo_1.png")); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 110, 130));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\THIERRY\\Desktop\\Projet MOBILE\\TEMPLATE\\01\\PJAVA\\src\\Icon\\Kia Seltos_1.jpeg")); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 820));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LogoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutBtnActionPerformed
              Login LoginFrame = new Login();
              LoginFrame.setVisible(true);
              LoginFrame.pack();
              LoginFrame.setLocationRelativeTo(null); 
              this.dispose();
    }//GEN-LAST:event_LogoutBtnActionPerformed

    private void SuivantbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SuivantbtnActionPerformed
        // TODO add your handling code here:
        Menu MenuFrame = new Menu();
              MenuFrame.setVisible(true);
              MenuFrame.pack();
              MenuFrame.setLocationRelativeTo(null); 
              this.dispose();
    }//GEN-LAST:event_SuivantbtnActionPerformed

    private void Suivantbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Suivantbtn1ActionPerformed
        // TODO add your handling code here:
        Reception ReceptionFrame = new Reception();
              ReceptionFrame.setVisible(true);
              ReceptionFrame.pack();
              ReceptionFrame.setLocationRelativeTo(null); 
              this.dispose();
    }//GEN-LAST:event_Suivantbtn1ActionPerformed

    private void Suivantbtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Suivantbtn2ActionPerformed
        // TODO add your handling code here:
        StatistiquesAnnuelles StatistiquesAnnuellesFrame = new StatistiquesAnnuelles();
              StatistiquesAnnuellesFrame.setVisible(true);
              StatistiquesAnnuellesFrame.pack();
              StatistiquesAnnuellesFrame.setLocationRelativeTo(null); 
              this.dispose();
    }//GEN-LAST:event_Suivantbtn2ActionPerformed

    private void Suivantbtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Suivantbtn3ActionPerformed
        // TODO add your handling code here:
         StatistiquesMensuelles  StatistiquesMensuellesFrame = new StatistiquesMensuelles ();
              StatistiquesMensuellesFrame.setVisible(true);
              StatistiquesMensuellesFrame.pack();
              StatistiquesMensuellesFrame.setLocationRelativeTo(null); 
              this.dispose();
    }//GEN-LAST:event_Suivantbtn3ActionPerformed
      
    public void setUser(String nom_utilisateur) {
    utilisateur.setText(nom_utilisateur);
}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LogoutBtn;
    private javax.swing.JButton Suivantbtn;
    private javax.swing.JButton Suivantbtn1;
    private javax.swing.JButton Suivantbtn2;
    private javax.swing.JButton Suivantbtn3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel utilisateur;
    // End of variables declaration//GEN-END:variables

}