/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetjava;

import javax.swing.table.DefaultTableModel;
import classe.GestionColis;
import classe.exportercolis;
import com.sun.glass.events.KeyEvent;
import java.awt.Color;
import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import java.sql.Date;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class Info extends javax.swing.JFrame {

    /**
     * Creates new form Info
     */
    public Info() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtprixm = new javax.swing.JTextField();
        txtlibellem = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabgestion = new javax.swing.JTable();
        txtnum = new javax.swing.JTextField();
        txtpoid = new javax.swing.JTextField();
        btnmodifier = new javax.swing.JButton();
        btnsupprimer = new javax.swing.JButton();
        btnexporter = new javax.swing.JButton();
        btnactualiser = new javax.swing.JButton();
        txtnom = new javax.swing.JTextField();
        txtprenom = new javax.swing.JTextField();
        txttel = new javax.swing.JTextField();
        txtnump = new javax.swing.JTextField();
        txttp = new javax.swing.JTextField();
        txtvilleE = new javax.swing.JTextField();
        txtnomD = new javax.swing.JTextField();
        txtprenomD = new javax.swing.JTextField();
        txtTelD = new javax.swing.JTextField();
        txtvilleD = new javax.swing.JTextField();
        txtdate = new javax.swing.JTextField();
        txtcout = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txttype = new javax.swing.JTextField();
        btnfacture = new javax.swing.JButton();

        txtprixm.setFont(new java.awt.Font("Comic Sans MS", 0, 15)); // NOI18N
        txtprixm.setEnabled(false);
        txtprixm.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtprixmFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtprixmFocusLost(evt);
            }
        });
        txtprixm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtprixmActionPerformed(evt);
            }
        });
        txtprixm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtprixmKeyPressed(evt);
            }
        });

        txtlibellem.setFont(new java.awt.Font("Comic Sans MS", 0, 15)); // NOI18N
        txtlibellem.setEnabled(false);
        txtlibellem.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtlibellemFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtlibellemFocusLost(evt);
            }
        });
        txtlibellem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtlibellemActionPerformed(evt);
            }
        });
        txtlibellem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtlibellemKeyPressed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("SimSun-ExtB", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Liste des enregistrements");

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tabgestion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "N", "Type", "Poids", "numeo_envoi", "NomE", "prenomE", "TelE", "num_pieceE", "Type_pieceE", "VilleE", "NomD", "PrenomD", "TelD", "VilleD", "Date_envoi", "Cout_envoi"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabgestion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabgestionMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabgestion);
        if (tabgestion.getColumnModel().getColumnCount() > 0) {
            tabgestion.getColumnModel().getColumn(1).setResizable(false);
        }

        txtnum.setFont(new java.awt.Font("Comic Sans MS", 0, 15)); // NOI18N
        txtnum.setEnabled(false);
        txtnum.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtnumFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtnumFocusLost(evt);
            }
        });
        txtnum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnumActionPerformed(evt);
            }
        });
        txtnum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnumKeyPressed(evt);
            }
        });

        txtpoid.setFont(new java.awt.Font("Comic Sans MS", 0, 15)); // NOI18N
        txtpoid.setEnabled(false);
        txtpoid.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtpoidFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtpoidFocusLost(evt);
            }
        });
        txtpoid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpoidActionPerformed(evt);
            }
        });
        txtpoid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtpoidKeyPressed(evt);
            }
        });

        btnmodifier.setBackground(new java.awt.Color(255, 255, 255));
        btnmodifier.setFont(new java.awt.Font("SimSun-ExtB", 1, 24)); // NOI18N
        btnmodifier.setText("Modifier");
        btnmodifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodifierActionPerformed(evt);
            }
        });

        btnsupprimer.setBackground(new java.awt.Color(255, 255, 255));
        btnsupprimer.setFont(new java.awt.Font("SimSun-ExtB", 1, 24)); // NOI18N
        btnsupprimer.setText("Supprimer");
        btnsupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsupprimerActionPerformed(evt);
            }
        });

        btnexporter.setBackground(new java.awt.Color(255, 255, 255));
        btnexporter.setFont(new java.awt.Font("SimSun-ExtB", 1, 24)); // NOI18N
        btnexporter.setText("Exporter");
        btnexporter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexporterActionPerformed(evt);
            }
        });

        btnactualiser.setBackground(new java.awt.Color(255, 255, 255));
        btnactualiser.setFont(new java.awt.Font("SimSun-ExtB", 1, 24)); // NOI18N
        btnactualiser.setText("Actualiser");
        btnactualiser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnactualiserActionPerformed(evt);
            }
        });

        txtnom.setFont(new java.awt.Font("Comic Sans MS", 0, 15)); // NOI18N
        txtnom.setEnabled(false);
        txtnom.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtnomFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtnomFocusLost(evt);
            }
        });
        txtnom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnomActionPerformed(evt);
            }
        });
        txtnom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnomKeyPressed(evt);
            }
        });

        txtprenom.setFont(new java.awt.Font("Comic Sans MS", 0, 15)); // NOI18N
        txtprenom.setEnabled(false);
        txtprenom.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtprenomFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtprenomFocusLost(evt);
            }
        });
        txtprenom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtprenomActionPerformed(evt);
            }
        });
        txtprenom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtprenomKeyPressed(evt);
            }
        });

        txttel.setFont(new java.awt.Font("Comic Sans MS", 0, 15)); // NOI18N
        txttel.setEnabled(false);
        txttel.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txttelFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txttelFocusLost(evt);
            }
        });
        txttel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttelActionPerformed(evt);
            }
        });
        txttel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txttelKeyPressed(evt);
            }
        });

        txtnump.setFont(new java.awt.Font("Comic Sans MS", 0, 15)); // NOI18N
        txtnump.setEnabled(false);
        txtnump.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtnumpFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtnumpFocusLost(evt);
            }
        });
        txtnump.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnumpActionPerformed(evt);
            }
        });
        txtnump.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnumpKeyPressed(evt);
            }
        });

        txttp.setFont(new java.awt.Font("Comic Sans MS", 0, 15)); // NOI18N
        txttp.setEnabled(false);
        txttp.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txttpFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txttpFocusLost(evt);
            }
        });
        txttp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttpActionPerformed(evt);
            }
        });
        txttp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txttpKeyPressed(evt);
            }
        });

        txtvilleE.setFont(new java.awt.Font("Comic Sans MS", 0, 15)); // NOI18N
        txtvilleE.setEnabled(false);
        txtvilleE.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtvilleEFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtvilleEFocusLost(evt);
            }
        });
        txtvilleE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtvilleEActionPerformed(evt);
            }
        });
        txtvilleE.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtvilleEKeyPressed(evt);
            }
        });

        txtnomD.setFont(new java.awt.Font("Comic Sans MS", 0, 15)); // NOI18N
        txtnomD.setEnabled(false);
        txtnomD.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtnomDFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtnomDFocusLost(evt);
            }
        });
        txtnomD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnomDActionPerformed(evt);
            }
        });
        txtnomD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnomDKeyPressed(evt);
            }
        });

        txtprenomD.setFont(new java.awt.Font("Comic Sans MS", 0, 15)); // NOI18N
        txtprenomD.setEnabled(false);
        txtprenomD.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtprenomDFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtprenomDFocusLost(evt);
            }
        });
        txtprenomD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtprenomDActionPerformed(evt);
            }
        });
        txtprenomD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtprenomDKeyPressed(evt);
            }
        });

        txtTelD.setFont(new java.awt.Font("Comic Sans MS", 0, 15)); // NOI18N
        txtTelD.setEnabled(false);
        txtTelD.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTelDFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTelDFocusLost(evt);
            }
        });
        txtTelD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelDActionPerformed(evt);
            }
        });
        txtTelD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTelDKeyPressed(evt);
            }
        });

        txtvilleD.setFont(new java.awt.Font("Comic Sans MS", 0, 15)); // NOI18N
        txtvilleD.setEnabled(false);
        txtvilleD.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtvilleDFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtvilleDFocusLost(evt);
            }
        });
        txtvilleD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtvilleDActionPerformed(evt);
            }
        });
        txtvilleD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtvilleDKeyPressed(evt);
            }
        });

        txtdate.setFont(new java.awt.Font("Comic Sans MS", 0, 15)); // NOI18N
        txtdate.setEnabled(false);
        txtdate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtdateFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtdateFocusLost(evt);
            }
        });
        txtdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdateActionPerformed(evt);
            }
        });
        txtdate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtdateKeyPressed(evt);
            }
        });

        txtcout.setFont(new java.awt.Font("Comic Sans MS", 0, 15)); // NOI18N
        txtcout.setEnabled(false);
        txtcout.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtcoutFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtcoutFocusLost(evt);
            }
        });
        txtcout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcoutActionPerformed(evt);
            }
        });
        txtcout.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcoutKeyPressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("SimSun-ExtB", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Colis");

        txttype.setFont(new java.awt.Font("Comic Sans MS", 0, 15)); // NOI18N
        txttype.setEnabled(false);
        txttype.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txttypeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txttypeFocusLost(evt);
            }
        });
        txttype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttypeActionPerformed(evt);
            }
        });
        txttype.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txttypeKeyPressed(evt);
            }
        });

        btnfacture.setBackground(new java.awt.Color(255, 255, 255));
        btnfacture.setFont(new java.awt.Font("SimSun-ExtB", 1, 24)); // NOI18N
        btnfacture.setText("Facture");
        btnfacture.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfactureActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(437, 437, 437)
                        .addComponent(btnmodifier)
                        .addGap(66, 66, 66)
                        .addComponent(btnsupprimer)
                        .addGap(95, 95, 95)
                        .addComponent(btnexporter)
                        .addGap(54, 54, 54)
                        .addComponent(btnfacture))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtpoid, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtnum, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtnom, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtprenom, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txttel, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtnump, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txttp, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtvilleE, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtnomD, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtprenomD, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtTelD, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtvilleD, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(txtdate, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtcout, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1255, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(214, 214, 214)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txttype, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(104, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(233, 233, 233)
                    .addComponent(btnactualiser)
                    .addContainerGap(1045, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txttype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtnump, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtpoid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtnum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtnom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtprenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txttel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtvilleE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtnomD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txttp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtprenomD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtTelD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtvilleD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtcout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnmodifier)
                    .addComponent(btnsupprimer)
                    .addComponent(btnexporter)
                    .addComponent(btnfacture))
                .addGap(21, 21, 21))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(495, Short.MAX_VALUE)
                    .addComponent(btnactualiser)
                    .addGap(23, 23, 23)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(559, 559, 559)
                .addComponent(jLabel1)
                .addContainerGap(603, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        setBounds(0, 0, 1550, 799);
    }// </editor-fold>//GEN-END:initComponents

    private void tabgestionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabgestionMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tabgestionMouseClicked

    private void txtprixmFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtprixmFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtprixmFocusGained

    private void txtprixmFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtprixmFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtprixmFocusLost

    private void txtprixmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtprixmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtprixmActionPerformed

    private void txtprixmKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtprixmKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtprixmKeyPressed

    private void txtlibellemFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtlibellemFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtlibellemFocusGained

    private void txtlibellemFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtlibellemFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtlibellemFocusLost

    private void txtlibellemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtlibellemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtlibellemActionPerformed

    private void txtlibellemKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtlibellemKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtlibellemKeyPressed

    private void txtnumFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnumFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnumFocusGained

    private void txtnumFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnumFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnumFocusLost

    private void txtnumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnumActionPerformed

    private void txtnumKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnumKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnumKeyPressed

    private void txtpoidFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtpoidFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpoidFocusGained

    private void txtpoidFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtpoidFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpoidFocusLost

    private void txtpoidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpoidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpoidActionPerformed

    private void txtpoidKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpoidKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpoidKeyPressed

    private void btnmodifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodifierActionPerformed
        // TODO add your handling code here:
        String type_colis=tabgestion.getValueAt(tabgestion.getSelectedRow(), 1).toString(),
                poids=txtpoid.getText(), numero_envoi=txtnum.getText(), nomE=txtnom.getText(), prenomE=txtprenom.getText(), telephoneE=txttel.getText(), numero_pieceE=txtnump.getText(), type_pieceE=txttp.getText(),
                 villeE=txtvilleE.getText(), nomD=txtnomD.getText(), prenomD=txtprenomD.getText(), telephoneD=txtTelD.getText(), villeD=txtvilleD.getText(), date_envoi=txtdate.getText(),
                 coutEnvoi=txtcout.getText();
         try {
    SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            java.util.Date dateEnvoi = dateFormat.parse(date_envoi);
    
    GestionColis.modifier(type_colis, Double.parseDouble(poids), numero_envoi, nomE, prenomE, telephoneE, 
                          numero_pieceE, type_pieceE, villeE, nomD, prenomD, telephoneD, villeD, (Date) dateEnvoi, 
                          Double.parseDouble(coutEnvoi));
} catch (ParseException e) {
    e.printStackTrace();
    // Gérer l'exception de parsing ici
}

        
        DefaultTableModel ta=(DefaultTableModel) tabgestion.getModel();
        ta.setRowCount(0);
        GestionColis.actualiser(ta);
        txtpoid.setText("");
        txtpoid.setEnabled(false);
        txtnum.setEnabled(false);
        txtnum.setText("");
        txtnom.setEnabled(false);
        txtnom.setText("");
        txtprenom.setEnabled(false);
        txtprenom.setText("");
        txttel.setEnabled(false);
        txttel.setText("");
        txtnump.setEnabled(false);
        txtnump.setText("");
        txttp.setEnabled(false);
        txttp.setText("");
        txtvilleE.setEnabled(false);
        txtvilleE.setText("");
        txtnomD.setEnabled(false);
        txtnomD.setText("");
        txtprenomD.setEnabled(false);
        txtprenomD.setText("");
        txtTelD.setEnabled(false);
        txtTelD.setText("");
        txtvilleD.setEnabled(false);
        txtvilleD.setText("");
        txtdate.setEnabled(false);
        txtdate.setText("");
        txtcout.setEnabled(false);
        txtcout.setText("");
        btnmodifier.setEnabled(false);
        btnsupprimer.setEnabled(false);
        
    }//GEN-LAST:event_btnmodifierActionPerformed

    private void btnsupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsupprimerActionPerformed
        // TODO add your handling code here:
         String type_piece=tabgestion.getValueAt(tabgestion.getSelectedRow(), 1).toString(),
                poids=txtpoid.getText(), numero_envoi=txtnum.getText(), nomE=txtnom.getText(), prenomE=txtprenom.getText(), telephoneE=txttel.getText(), numero_pieceE=txtnump.getText(), type_pieceE=txttp.getText(),
                 villeE=txtvilleE.getText(), nomD=txtnomD.getText(), prenomD=txtprenomD.getText(), telephoneD=txtTelD.getText(), villeD=txtvilleD.getText(), date_envoi=txtdate.getText(),
                 coutEnvoi=txtcout.getText();
        GestionColis.supprimer(type_piece);
        DefaultTableModel ta=(DefaultTableModel) tabgestion.getModel();
        ta.setRowCount(0);
        GestionColis.actualiser(ta);
        txtpoid.setText("");
        txtpoid.setEnabled(false);
        txtnum.setEnabled(false);
        txtnum.setText("");
        txtnom.setEnabled(false);
        txtnom.setText("");
        txtprenom.setEnabled(false);
        txtprenom.setText("");
        txttel.setEnabled(false);
        txttel.setText("");
        txtnump.setEnabled(false);
        txtnump.setText("");
        txttp.setEnabled(false);
        txttp.setText("");
        txtvilleE.setEnabled(false);
        txtvilleE.setText("");
        txtnomD.setEnabled(false);
        txtnomD.setText("");
        txtprenomD.setEnabled(false);
        txtprenomD.setText("");
        txtTelD.setEnabled(false);
        txtTelD.setText("");
        txtvilleD.setEnabled(false);
        txtvilleD.setText("");
        txtdate.setEnabled(false);
        txtdate.setText("");
        txtcout.setEnabled(false);
        txtcout.setText("");
        btnmodifier.setEnabled(false);
        btnsupprimer.setEnabled(false);
    }//GEN-LAST:event_btnsupprimerActionPerformed

    private void btnexporterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexporterActionPerformed
        // TODO add your handling code here:
         DefaultTableModel tm=(DefaultTableModel) tabgestion.getModel();
        exportercolis.exporter(tm);
        Desktop dk=Desktop.getDesktop();
        try {
            dk.open(new File("C:/Users/Public/liste.xls"));
        } catch (IOException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnexporterActionPerformed

    private void btnactualiserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnactualiserActionPerformed
        // TODO add your handling code here:
        DefaultTableModel ta=(DefaultTableModel) tabgestion.getModel();
        /*vider*/
        ta.setRowCount(0);
        GestionColis.actualiser(ta);
        if(tabgestion.getRowCount()!=0){
            btnexporter.setEnabled(true);}
        else btnexporter.setEnabled(false);
        
    }//GEN-LAST:event_btnactualiserActionPerformed

    private void txtnomFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnomFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnomFocusGained

    private void txtnomFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnomFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnomFocusLost

    private void txtnomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnomActionPerformed

    private void txtnomKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnomKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnomKeyPressed

    private void txtprenomFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtprenomFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtprenomFocusGained

    private void txtprenomFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtprenomFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtprenomFocusLost

    private void txtprenomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtprenomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtprenomActionPerformed

    private void txtprenomKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtprenomKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtprenomKeyPressed

    private void txttelFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txttelFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txttelFocusGained

    private void txttelFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txttelFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txttelFocusLost

    private void txttelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttelActionPerformed

    private void txttelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttelKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttelKeyPressed

    private void txtnumpFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnumpFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnumpFocusGained

    private void txtnumpFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnumpFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnumpFocusLost

    private void txtnumpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnumpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnumpActionPerformed

    private void txtnumpKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnumpKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnumpKeyPressed

    private void txttpFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txttpFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txttpFocusGained

    private void txttpFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txttpFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txttpFocusLost

    private void txttpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttpActionPerformed

    private void txttpKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttpKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttpKeyPressed

    private void txtvilleEFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtvilleEFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtvilleEFocusGained

    private void txtvilleEFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtvilleEFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtvilleEFocusLost

    private void txtvilleEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtvilleEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtvilleEActionPerformed

    private void txtvilleEKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtvilleEKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtvilleEKeyPressed

    private void txtnomDFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnomDFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnomDFocusGained

    private void txtnomDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnomDFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnomDFocusLost

    private void txtnomDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnomDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnomDActionPerformed

    private void txtnomDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnomDKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnomDKeyPressed

    private void txtprenomDFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtprenomDFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtprenomDFocusGained

    private void txtprenomDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtprenomDFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtprenomDFocusLost

    private void txtprenomDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtprenomDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtprenomDActionPerformed

    private void txtprenomDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtprenomDKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtprenomDKeyPressed

    private void txtTelDFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTelDFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelDFocusGained

    private void txtTelDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTelDFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelDFocusLost

    private void txtTelDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelDActionPerformed

    private void txtTelDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelDKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelDKeyPressed

    private void txtvilleDFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtvilleDFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtvilleDFocusGained

    private void txtvilleDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtvilleDFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtvilleDFocusLost

    private void txtvilleDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtvilleDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtvilleDActionPerformed

    private void txtvilleDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtvilleDKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtvilleDKeyPressed

    private void txtdateFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtdateFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdateFocusGained

    private void txtdateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtdateFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdateFocusLost

    private void txtdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdateActionPerformed

    private void txtdateKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdateKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdateKeyPressed

    private void txtcoutFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtcoutFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcoutFocusGained

    private void txtcoutFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtcoutFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcoutFocusLost

    private void txtcoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcoutActionPerformed

    private void txtcoutKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcoutKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcoutKeyPressed

    private void txttypeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txttypeFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txttypeFocusGained

    private void txttypeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txttypeFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txttypeFocusLost

    private void txttypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttypeActionPerformed

    private void txttypeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttypeKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttypeKeyPressed

    private void btnfactureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfactureActionPerformed
        // TODO add your handling code here:
        Facture FactureFrame = new Facture();
              FactureFrame.setVisible(true);
              FactureFrame.pack();
              FactureFrame.setLocationRelativeTo(null); 
              this.dispose();
    }//GEN-LAST:event_btnfactureActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Info().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnactualiser;
    private javax.swing.JButton btnexporter;
    private javax.swing.JButton btnfacture;
    private javax.swing.JButton btnmodifier;
    private javax.swing.JButton btnsupprimer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabgestion;
    private javax.swing.JTextField txtTelD;
    private javax.swing.JTextField txtcout;
    private javax.swing.JTextField txtdate;
    private javax.swing.JTextField txtlibellem;
    private javax.swing.JTextField txtnom;
    private javax.swing.JTextField txtnomD;
    private javax.swing.JTextField txtnum;
    private javax.swing.JTextField txtnump;
    private javax.swing.JTextField txtpoid;
    private javax.swing.JTextField txtprenom;
    private javax.swing.JTextField txtprenomD;
    private javax.swing.JTextField txtprixm;
    private javax.swing.JTextField txttel;
    private javax.swing.JTextField txttp;
    private javax.swing.JTextField txttype;
    private javax.swing.JTextField txtvilleD;
    private javax.swing.JTextField txtvilleE;
    // End of variables declaration//GEN-END:variables
}
