/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetjava;

import classe.GestionColis;
import javax.swing.*;
import java.text.SimpleDateFormat;
import classe.exportercolis;
import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import java.sql.Date;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class Infor extends javax.swing.JFrame {

    /**
     * Creates new form Infor
     */
    public Infor() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabgestione = new javax.swing.JTable();
        txtnomr = new javax.swing.JTextField();
        btnmodifierr = new javax.swing.JButton();
        btnsupprimer = new javax.swing.JButton();
        btnexporterr = new javax.swing.JButton();
        btnactualiserr = new javax.swing.JButton();
        txtprenomr = new javax.swing.JTextField();
        txttelr = new javax.swing.JTextField();
        txtnumpr = new javax.swing.JTextField();
        txttpr = new javax.swing.JTextField();
        txtdater = new javax.swing.JTextField();
        txtnenr = new javax.swing.JTextField();
        txtpenr = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtnumr = new javax.swing.JTextField();
        btnfacture = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("SimSun-ExtB", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Liste des Receptions");

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tabgestione.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "N", "Num_envoie", "Nom_recepteur", "Prenom_recepteur", "Telephone", "Numero_piece", "Type_piece", "Date_reception", "Nom_envoyeur", "Prenom_envoyeur"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabgestione.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabgestioneMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabgestione);

        txtnomr.setFont(new java.awt.Font("Comic Sans MS", 0, 15)); // NOI18N
        txtnomr.setEnabled(false);
        txtnomr.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtnomrFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtnomrFocusLost(evt);
            }
        });
        txtnomr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnomrActionPerformed(evt);
            }
        });
        txtnomr.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnomrKeyPressed(evt);
            }
        });

        btnmodifierr.setBackground(new java.awt.Color(255, 255, 255));
        btnmodifierr.setFont(new java.awt.Font("SimSun-ExtB", 1, 24)); // NOI18N
        btnmodifierr.setText("Modifier");
        btnmodifierr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodifierrActionPerformed(evt);
            }
        });

        btnsupprimer.setBackground(new java.awt.Color(255, 255, 255));
        btnsupprimer.setFont(new java.awt.Font("SimSun-ExtB", 1, 24)); // NOI18N
        btnsupprimer.setText("Supprimer");
        btnsupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsupprimerActionPerformed(evt);
            }
        });

        btnexporterr.setBackground(new java.awt.Color(255, 255, 255));
        btnexporterr.setFont(new java.awt.Font("SimSun-ExtB", 1, 24)); // NOI18N
        btnexporterr.setText("Exporter");
        btnexporterr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexporterrActionPerformed(evt);
            }
        });

        btnactualiserr.setBackground(new java.awt.Color(255, 255, 255));
        btnactualiserr.setFont(new java.awt.Font("SimSun-ExtB", 1, 24)); // NOI18N
        btnactualiserr.setText("Actualiser");
        btnactualiserr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnactualiserrActionPerformed(evt);
            }
        });

        txtprenomr.setFont(new java.awt.Font("Comic Sans MS", 0, 15)); // NOI18N
        txtprenomr.setEnabled(false);
        txtprenomr.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtprenomrFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtprenomrFocusLost(evt);
            }
        });
        txtprenomr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtprenomrActionPerformed(evt);
            }
        });
        txtprenomr.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtprenomrKeyPressed(evt);
            }
        });

        txttelr.setFont(new java.awt.Font("Comic Sans MS", 0, 15)); // NOI18N
        txttelr.setEnabled(false);
        txttelr.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txttelrFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txttelrFocusLost(evt);
            }
        });
        txttelr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttelrActionPerformed(evt);
            }
        });
        txttelr.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txttelrKeyPressed(evt);
            }
        });

        txtnumpr.setFont(new java.awt.Font("Comic Sans MS", 0, 15)); // NOI18N
        txtnumpr.setEnabled(false);
        txtnumpr.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtnumprFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtnumprFocusLost(evt);
            }
        });
        txtnumpr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnumprActionPerformed(evt);
            }
        });
        txtnumpr.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnumprKeyPressed(evt);
            }
        });

        txttpr.setFont(new java.awt.Font("Comic Sans MS", 0, 15)); // NOI18N
        txttpr.setEnabled(false);
        txttpr.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txttprFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txttprFocusLost(evt);
            }
        });
        txttpr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttprActionPerformed(evt);
            }
        });
        txttpr.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txttprKeyPressed(evt);
            }
        });

        txtdater.setFont(new java.awt.Font("Comic Sans MS", 0, 15)); // NOI18N
        txtdater.setEnabled(false);
        txtdater.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtdaterFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtdaterFocusLost(evt);
            }
        });
        txtdater.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdaterActionPerformed(evt);
            }
        });
        txtdater.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtdaterKeyPressed(evt);
            }
        });

        txtnenr.setFont(new java.awt.Font("Comic Sans MS", 0, 15)); // NOI18N
        txtnenr.setEnabled(false);
        txtnenr.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtnenrFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtnenrFocusLost(evt);
            }
        });
        txtnenr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnenrActionPerformed(evt);
            }
        });
        txtnenr.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnenrKeyPressed(evt);
            }
        });

        txtpenr.setFont(new java.awt.Font("Comic Sans MS", 0, 15)); // NOI18N
        txtpenr.setEnabled(false);
        txtpenr.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtpenrFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtpenrFocusLost(evt);
            }
        });
        txtpenr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpenrActionPerformed(evt);
            }
        });
        txtpenr.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtpenrKeyPressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("SimSun-ExtB", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Numero");

        txtnumr.setFont(new java.awt.Font("Comic Sans MS", 0, 15)); // NOI18N
        txtnumr.setEnabled(false);
        txtnumr.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtnumrFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtnumrFocusLost(evt);
            }
        });
        txtnumr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnumrActionPerformed(evt);
            }
        });
        txtnumr.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnumrKeyPressed(evt);
            }
        });

        btnfacture.setBackground(new java.awt.Color(255, 255, 255));
        btnfacture.setFont(new java.awt.Font("SimSun-ExtB", 1, 24)); // NOI18N
        btnfacture.setText("Facture");
        btnfacture.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfactureActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(437, 437, 437)
                        .addComponent(btnmodifierr)
                        .addGap(66, 66, 66)
                        .addComponent(btnsupprimer)
                        .addGap(95, 95, 95)
                        .addComponent(btnexporterr)
                        .addGap(54, 54, 54)
                        .addComponent(btnfacture))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1255, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(txtnomr, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtprenomr, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(txttelr, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(54, 54, 54)
                                .addComponent(txtnumpr, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(txttpr, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(txtdater, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(txtnenr, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtpenr, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(214, 214, 214)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtnumr, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(156, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(233, 233, 233)
                    .addComponent(btnactualiserr)
                    .addContainerGap(1045, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtnumr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txttpr, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtdater, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtnenr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtpenr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtnumpr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txttelr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtprenomr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtnomr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnmodifierr)
                    .addComponent(btnsupprimer)
                    .addComponent(btnexporterr)
                    .addComponent(btnfacture))
                .addGap(21, 21, 21))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(495, Short.MAX_VALUE)
                    .addComponent(btnactualiserr)
                    .addGap(23, 23, 23)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(673, 673, 673)
                .addComponent(jLabel1)
                .addContainerGap(935, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(181, 181, 181)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(182, 182, 182)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addContainerGap(676, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(89, 89, 89)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(89, 89, 89)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabgestioneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabgestioneMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_tabgestioneMouseClicked

    private void txtnomrFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnomrFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnomrFocusGained

    private void txtnomrFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnomrFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnomrFocusLost

    private void txtnomrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnomrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnomrActionPerformed

    private void txtnomrKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnomrKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnomrKeyPressed

    private void btnmodifierrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodifierrActionPerformed
        // TODO add your handling code here:
        String numero_envoie=tabgestione.getValueAt(tabgestione.getSelectedRow(), 1).toString(),
        nom_recepteur=txtnomr.getText(), prenom_recepteur=txtprenomr.getText(),telephone_recepteur =txttelr.getText(), numero_piece_recepteur=txtnumpr.getText(), type_piece_recepteur=txttpr.getText(), date_reception=txtdater.getText(), nomEr=txtnenr.getText(),
        prenomEr=txtpenr.getText();
        
       GestionColis.modifierReception(numero_envoie,  nom_recepteur, prenom_recepteur, telephone_recepteur,  numero_piece_recepteur, 
                          type_piece_recepteur, date_reception, nomEr, prenomEr);
  
        DefaultTableModel ta=(DefaultTableModel) tabgestione.getModel();
        ta.setRowCount(0);
        GestionColis.actualiserReception(ta);
        txtnomr.setEnabled(false);
        txtnomr.setText("");
        txtprenomr.setEnabled(false);
        txtprenomr.setText("");
        txttelr.setEnabled(false);
        txttelr.setText("");
        txtnumpr.setEnabled(false);
        txtnumpr.setText("");
        txttpr.setEnabled(false);
        txttpr.setText("");
        txtdater.setEnabled(false);
        txtdater.setText("");
        txtnenr.setEnabled(false);
        txtnenr.setText("");
        txtpenr.setEnabled(false);
        txtpenr.setText("");
        btnmodifierr.setEnabled(false);
        btnsupprimer.setEnabled(false);

    }//GEN-LAST:event_btnmodifierrActionPerformed

    private void btnsupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsupprimerActionPerformed
        // TODO add your handling code here:
        String numero_envoie=tabgestione.getValueAt(tabgestione.getSelectedRow(), 1).toString(),
        nom_recepteur=txtnomr.getText(), prenom_recepteur=txtprenomr.getText(),telephone_recepteur =txttelr.getText(), numero_piece_recepteur=txtnumpr.getText(), type_piece_recepteur=txttpr.getText(), date_reception=txtdater.getText(), nomEr=txtnenr.getText(),
        prenomEr=txtpenr.getText();
        GestionColis.supprimerReception(numero_envoie);
        DefaultTableModel ta=(DefaultTableModel) tabgestione.getModel();
        ta.setRowCount(0);
        GestionColis.actualiserReception(ta);
        txtnomr.setEnabled(false);
        txtnomr.setText("");
        txtprenomr.setEnabled(false);
        txtprenomr.setText("");
        txttelr.setEnabled(false);
        txttelr.setText("");
        txtnumpr.setEnabled(false);
        txtnumpr.setText("");
        txttpr.setEnabled(false);
        txttpr.setText("");
        txtdater.setEnabled(false);
        txtdater.setText("");
        txtnenr.setEnabled(false);
        txtnenr.setText("");
        txtpenr.setEnabled(false);
        txtpenr.setText("");
        btnmodifierr.setEnabled(false);
        btnsupprimer.setEnabled(false);
    }//GEN-LAST:event_btnsupprimerActionPerformed

    private void btnexporterrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexporterrActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tm=(DefaultTableModel) tabgestione.getModel();
        exportercolis.exporter(tm);
        Desktop dk=Desktop.getDesktop();
        try {
            dk.open(new File("C:/Users/Public/liste.xls"));
        } catch (IOException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnexporterrActionPerformed

    private void btnactualiserrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnactualiserrActionPerformed
        // TODO add your handling code here:
        DefaultTableModel ta=(DefaultTableModel) tabgestione.getModel();
        /*vider*/
        ta.setRowCount(0);
        GestionColis.actualiserReception(ta);
        if(tabgestione.getRowCount()!=0){
            btnexporterr.setEnabled(true);}
        else btnexporterr.setEnabled(false);

    }//GEN-LAST:event_btnactualiserrActionPerformed

    private void txtprenomrFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtprenomrFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtprenomrFocusGained

    private void txtprenomrFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtprenomrFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtprenomrFocusLost

    private void txtprenomrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtprenomrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtprenomrActionPerformed

    private void txtprenomrKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtprenomrKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtprenomrKeyPressed

    private void txttelrFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txttelrFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txttelrFocusGained

    private void txttelrFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txttelrFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txttelrFocusLost

    private void txttelrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttelrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttelrActionPerformed

    private void txttelrKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttelrKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttelrKeyPressed

    private void txtnumprFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnumprFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnumprFocusGained

    private void txtnumprFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnumprFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnumprFocusLost

    private void txtnumprActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnumprActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnumprActionPerformed

    private void txtnumprKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnumprKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnumprKeyPressed

    private void txttprFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txttprFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txttprFocusGained

    private void txttprFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txttprFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txttprFocusLost

    private void txttprActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttprActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttprActionPerformed

    private void txttprKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttprKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttprKeyPressed

    private void txtdaterFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtdaterFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdaterFocusGained

    private void txtdaterFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtdaterFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdaterFocusLost

    private void txtdaterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdaterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdaterActionPerformed

    private void txtdaterKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdaterKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdaterKeyPressed

    private void txtnenrFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnenrFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnenrFocusGained

    private void txtnenrFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnenrFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnenrFocusLost

    private void txtnenrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnenrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnenrActionPerformed

    private void txtnenrKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnenrKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnenrKeyPressed

    private void txtpenrFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtpenrFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpenrFocusGained

    private void txtpenrFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtpenrFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpenrFocusLost

    private void txtpenrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpenrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpenrActionPerformed

    private void txtpenrKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpenrKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpenrKeyPressed

    private void txtnumrFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnumrFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnumrFocusGained

    private void txtnumrFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnumrFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnumrFocusLost

    private void txtnumrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnumrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnumrActionPerformed

    private void txtnumrKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnumrKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnumrKeyPressed

    private void btnfactureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfactureActionPerformed
        // TODO add your handling code here:
        FactureR FactureRFrame = new FactureR();
        FactureRFrame.setVisible(true);
        FactureRFrame.pack();
        FactureRFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnfactureActionPerformed
 
 public void setUser(String numero_envoie) {
    txtnumr.setText(numero_envoie);
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Infor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Infor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Infor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Infor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Infor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnactualiserr;
    private javax.swing.JButton btnexporterr;
    private javax.swing.JButton btnfacture;
    private javax.swing.JButton btnmodifierr;
    private javax.swing.JButton btnsupprimer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabgestione;
    private javax.swing.JTextField txtdater;
    private javax.swing.JTextField txtnenr;
    private javax.swing.JTextField txtnomr;
    private javax.swing.JTextField txtnumpr;
    private javax.swing.JTextField txtnumr;
    private javax.swing.JTextField txtpenr;
    private javax.swing.JTextField txtprenomr;
    private javax.swing.JTextField txttelr;
    private javax.swing.JTextField txttpr;
    // End of variables declaration//GEN-END:variables
}
