/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetjava;

import java.sql.*;
import classe.GestionColis;
import classe.exportercolis;
import com.sun.glass.events.KeyEvent;
import java.awt.Color;
import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author HP
 */
public class Menu extends javax.swing.JFrame {
public static Connection c, ce;
    public static Statement st, ste;
    public static ResultSet rs, rse;
    public static PreparedStatement ps, pse;
    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        dpane = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtpoid = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtnom = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtprenom = new javax.swing.JTextField();
        txtnum = new javax.swing.JTextField();
        txttype = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txttel = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtnump = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txttp = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtville = new javax.swing.JTextField();
        txtnomd = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtprenomd = new javax.swing.JTextField();
        txtDate = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtvilled = new javax.swing.JTextField();
        txtTel = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtcout = new javax.swing.JTextField();
        btnnouveau = new javax.swing.JButton();
        btnvalider = new javax.swing.JButton();
        Quitterbtn = new javax.swing.JButton();
        btnliste = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));

        jLabel6.setFont(new java.awt.Font("SimSun-ExtB", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Type");

        jTextField5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        dpane.setBackground(new java.awt.Color(0, 51, 51));

        jLabel1.setFont(new java.awt.Font("SimSun-ExtB", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ENREGISTRER UN COLIS");

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setFont(new java.awt.Font("SimSun-ExtB", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Type");

        jLabel3.setFont(new java.awt.Font("SimSun-ExtB", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Poids");

        txtpoid.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtpoid.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtpoidFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtpoidFocusLost(evt);
            }
        });
        txtpoid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpoidActionPerformed(evt);
            }
        });
        txtpoid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtpoidKeyPressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("SimSun-ExtB", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("NumeroEnvoi");

        jLabel5.setFont(new java.awt.Font("SimSun-ExtB", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("NomEnvoyeur");

        txtnom.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtnom.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtnomFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtnomFocusLost(evt);
            }
        });
        txtnom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnomActionPerformed(evt);
            }
        });
        txtnom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnomKeyPressed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("SimSun-ExtB", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("PrenomEnvoyeur");

        txtprenom.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtprenom.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtprenomFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtprenomFocusLost(evt);
            }
        });
        txtprenom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtprenomActionPerformed(evt);
            }
        });
        txtprenom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtprenomKeyPressed(evt);
            }
        });

        txtnum.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtnum.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtnumFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtnumFocusLost(evt);
            }
        });
        txtnum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnumActionPerformed(evt);
            }
        });
        txtnum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnumKeyPressed(evt);
            }
        });

        txttype.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txttype.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txttypeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txttypeFocusLost(evt);
            }
        });
        txttype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttypeActionPerformed(evt);
            }
        });
        txttype.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txttypeKeyPressed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("SimSun-ExtB", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("telEnvoyeur");

        txttel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txttel.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txttelFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txttelFocusLost(evt);
            }
        });
        txttel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttelActionPerformed(evt);
            }
        });
        txttel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txttelKeyPressed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("SimSun-ExtB", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("NumpieceEnvoyeur");

        txtnump.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtnump.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtnumpFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtnumpFocusLost(evt);
            }
        });
        txtnump.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnumpActionPerformed(evt);
            }
        });
        txtnump.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnumpKeyPressed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("SimSun-ExtB", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("TypepieceEnvoyeu");

        txttp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txttp.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txttpFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txttpFocusLost(evt);
            }
        });
        txttp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttpActionPerformed(evt);
            }
        });
        txttp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txttpKeyPressed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("SimSun-ExtB", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("VilleEnvoeyeur");

        txtville.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtville.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtvilleFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtvilleFocusLost(evt);
            }
        });
        txtville.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtvilleActionPerformed(evt);
            }
        });
        txtville.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtvilleKeyPressed(evt);
            }
        });

        txtnomd.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtnomd.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtnomdFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtnomdFocusLost(evt);
            }
        });
        txtnomd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnomdActionPerformed(evt);
            }
        });
        txtnomd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnomdKeyPressed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("SimSun-ExtB", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("NomDestinataire");

        jLabel13.setFont(new java.awt.Font("SimSun-ExtB", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("PrenomDestinataire");

        txtprenomd.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtprenomd.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtprenomdFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtprenomdFocusLost(evt);
            }
        });
        txtprenomd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtprenomdActionPerformed(evt);
            }
        });
        txtprenomd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtprenomdKeyPressed(evt);
            }
        });

        txtDate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtDate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDateFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDateFocusLost(evt);
            }
        });
        txtDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDateActionPerformed(evt);
            }
        });
        txtDate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDateKeyPressed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("SimSun-ExtB", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("DateEnvoi");

        jLabel15.setFont(new java.awt.Font("SimSun-ExtB", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel15.setText("VilleDestinataire");

        txtvilled.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtvilled.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtvilledFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtvilledFocusLost(evt);
            }
        });
        txtvilled.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtvilledActionPerformed(evt);
            }
        });
        txtvilled.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtvilledKeyPressed(evt);
            }
        });

        txtTel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTel.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTelFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTelFocusLost(evt);
            }
        });
        txtTel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelActionPerformed(evt);
            }
        });
        txtTel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTelKeyPressed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("SimSun-ExtB", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel16.setText("TelephoneDestinataire");

        jLabel17.setFont(new java.awt.Font("SimSun-ExtB", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel17.setText("CoutEnvoi");

        txtcout.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtcout.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtcoutFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtcoutFocusLost(evt);
            }
        });
        txtcout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcoutActionPerformed(evt);
            }
        });
        txtcout.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcoutKeyPressed(evt);
            }
        });

        btnnouveau.setBackground(new java.awt.Color(255, 255, 255));
        btnnouveau.setFont(new java.awt.Font("SimSun-ExtB", 1, 24)); // NOI18N
        btnnouveau.setText("Nouveau");
        btnnouveau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnouveauActionPerformed(evt);
            }
        });

        btnvalider.setBackground(new java.awt.Color(255, 255, 255));
        btnvalider.setFont(new java.awt.Font("SimSun-ExtB", 1, 24)); // NOI18N
        btnvalider.setText("VALIDER");
        btnvalider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvaliderActionPerformed(evt);
            }
        });

        Quitterbtn.setBackground(new java.awt.Color(255, 255, 255));
        Quitterbtn.setFont(new java.awt.Font("SimSun-ExtB", 1, 24)); // NOI18N
        Quitterbtn.setText("Quitter");
        Quitterbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                QuitterbtnMouseClicked(evt);
            }
        });
        Quitterbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuitterbtnActionPerformed(evt);
            }
        });

        btnliste.setBackground(new java.awt.Color(255, 255, 255));
        btnliste.setFont(new java.awt.Font("SimSun-ExtB", 1, 24)); // NOI18N
        btnliste.setText("Liste Colis");
        btnliste.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnlisteMouseClicked(evt);
            }
        });
        btnliste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlisteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txttype))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtprenom, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtnom))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtnum, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txttel, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtpoid, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtnump, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txttp, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtville, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtnomd, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtvilled, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTel, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Quitterbtn))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtcout, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(87, 87, 87)
                                .addComponent(btnliste))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtprenomd, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addComponent(btnnouveau)
                .addGap(118, 118, 118)
                .addComponent(btnvalider)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txttp, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtcout, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 6, Short.MAX_VALUE))
                            .addComponent(txttype))))
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtville, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtpoid, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnum, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtnomd, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtprenomd, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(txtnom, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtprenom, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtTel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txttel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtvilled, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnump, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnnouveau)
                    .addComponent(btnvalider)
                    .addComponent(Quitterbtn)
                    .addComponent(btnliste))
                .addGap(405, 405, 405))
        );

        javax.swing.GroupLayout dpaneLayout = new javax.swing.GroupLayout(dpane);
        dpane.setLayout(dpaneLayout);
        dpaneLayout.setHorizontalGroup(
            dpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dpaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dpaneLayout.createSequentialGroup()
                .addContainerGap(87, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );
        dpaneLayout.setVerticalGroup(
            dpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dpaneLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(dpane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 154, Short.MAX_VALUE)
                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(419, 419, 419)
                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dpane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(1529, 825));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtpoidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpoidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpoidActionPerformed

    private void txtnomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnomActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void txtprenomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtprenomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtprenomActionPerformed

    private void txtnumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnumActionPerformed

    private void txttypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttypeActionPerformed

    private void txttelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttelActionPerformed

    private void txtnumpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnumpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnumpActionPerformed

    private void txttpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttpActionPerformed

    private void txtvilleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtvilleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtvilleActionPerformed

    private void txtnomdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnomdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnomdActionPerformed

    private void txtprenomdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtprenomdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtprenomdActionPerformed

    private void txtDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDateActionPerformed

    private void txtvilledActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtvilledActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtvilledActionPerformed

    private void txtTelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelActionPerformed

    private void txtcoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcoutActionPerformed

    private void btnvaliderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvaliderActionPerformed
        // TODO add your handling code here:
        String type_colis=txttype.getText(),numero_envoi=txtnum.getText(),nomE=txtnom.getText(),prenomE=txtprenom.getText(),telephoneE=txttel.getText(),numero_pieceE=txtnum.getText(),
                type_pieceE=txttp.getText(),villeE=txtville.getText(),nomD=txtnomd.getText(),prenomD=txtprenomd.getText(),telephoneD=txtTel.getText(),villeD=txtvilled.getText(),date_envoi=txtDate.getText();
        String poids = txtpoid.getText();     
        String coutEnvoi = txtcout.getText();
        double pp=Integer.parseInt(poids);
        double pc=Integer.parseInt(coutEnvoi);
        GestionColis.enregistrerColis(type_colis,pp,numero_envoi,nomE,prenomE,telephoneE,numero_pieceE,type_pieceE,villeE,nomD,prenomD,telephoneD,villeD,date_envoi,pc);
        
        
        txttype.setText("");
        txtpoid.setText("");
        txtnum.setText("");
         txtnom.setText("");
        txtprenom.setText("");
        txttel.setText("");
         txtnump.setText("");
        txttp.setText("");
        txtville.setText("");
         txtnomd.setText("");
        txtprenomd.setText("");
        txtTel.setText("");
         txtvilled.setText("");
        txtDate.setText("");
        txtcout.setText("");
        txttype.setEnabled(false);
        txtpoid.setEnabled(false);
        txtnum.setEnabled(false);
        txtnom.setEnabled(false);
        txtprenom.setEnabled(false);
        txttel.setEnabled(false);
        txtnump.setEnabled(false);
        txttp.setEnabled(false);
        txtville.setEnabled(false);
        txtnomd.setEnabled(false);
        txtprenomd.setEnabled(false);
        txtTel.setEnabled(false);
        txtvilled.setEnabled(false);
        txtDate.setEnabled(false);
        txtcout.setEnabled(false);
        btnvalider.setEnabled(false);
        btnnouveau.setEnabled(true);
        Info InfoFrame = new Info();
              InfoFrame.setVisible(true);
              InfoFrame.pack();
              InfoFrame.setLocationRelativeTo(null); 
              this.dispose();
    }//GEN-LAST:event_btnvaliderActionPerformed

    private void QuitterbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuitterbtnActionPerformed
        // TODO add your handling code here:
        Home HomeFrame = new Home();
              HomeFrame.setVisible(true);
              HomeFrame.pack();
              HomeFrame.setLocationRelativeTo(null); 
              this.dispose();
    }//GEN-LAST:event_QuitterbtnActionPerformed

    private void btnnouveauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnouveauActionPerformed
        // TODO add your handling code here:
        txttype.setEnabled(true);
        txtpoid.setEnabled(true);
        txtnum.setEnabled(true);
        txtnom.setEnabled(true);
        txtprenom.setEnabled(true);
        txttel.setEnabled(true);
        txtnump.setEnabled(true);
        txttp.setEnabled(true);
        txtville.setEnabled(true);
        txtnomd.setEnabled(true);
        txtprenomd.setEnabled(true);
        txtTel.setEnabled(true);
        txtvilled.setEnabled(true);
        txtDate.setEnabled(true);
        txtcout.setEnabled(true);
        btnnouveau.setEnabled(false);
        btnvalider.setEnabled(true);
        txttype.grabFocus();
    }//GEN-LAST:event_btnnouveauActionPerformed

    private void QuitterbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QuitterbtnMouseClicked
        // TODO add your handling code here:
        dpane.removeAll();
        dpane.repaint();
        //        appel jinternal frame
       Menu fg=new Menu();
       dpane.add(fg);
        fg.setVisible(true);
       
    }//GEN-LAST:event_QuitterbtnMouseClicked

    private void txttypeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txttypeFocusGained
        // TODO add your handling code here:
        txttype.setBackground(Color.ORANGE);
    }//GEN-LAST:event_txttypeFocusGained

    private void txtpoidFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtpoidFocusGained
        // TODO add your handling code here:
        txtpoid.setBackground(Color.ORANGE);
    }//GEN-LAST:event_txtpoidFocusGained

    private void txtnumFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnumFocusGained
        // TODO add your handling code here:
        txtnum.setBackground(Color.ORANGE);
    }//GEN-LAST:event_txtnumFocusGained

    private void txtnomFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnomFocusGained
        // TODO add your handling code here:
        txtnom.setBackground(Color.ORANGE);
    }//GEN-LAST:event_txtnomFocusGained

    private void txtprenomFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtprenomFocusGained
        // TODO add your handling code here:
        txtprenom.setBackground(Color.ORANGE);
    }//GEN-LAST:event_txtprenomFocusGained

    private void txttelFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txttelFocusGained
        // TODO add your handling code here:
        txttel.setBackground(Color.ORANGE);
    }//GEN-LAST:event_txttelFocusGained

    private void txtnumpFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnumpFocusGained
        // TODO add your handling code here:
        txtnump.setBackground(Color.ORANGE);
    }//GEN-LAST:event_txtnumpFocusGained

    private void txttpFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txttpFocusGained
        // TODO add your handling code here:
        txttp.setBackground(Color.ORANGE);
    }//GEN-LAST:event_txttpFocusGained

    private void txtvilleFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtvilleFocusGained
        // TODO add your handling code here:
        txtville.setBackground(Color.ORANGE);
    }//GEN-LAST:event_txtvilleFocusGained

    private void txtnomdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnomdFocusGained
        // TODO add your handling code here:
        txtnomd.setBackground(Color.ORANGE);
    }//GEN-LAST:event_txtnomdFocusGained

    private void txtprenomdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtprenomdFocusGained
        // TODO add your handling code here:
        txtprenomd.setBackground(Color.ORANGE);
    }//GEN-LAST:event_txtprenomdFocusGained

    private void txtTelFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTelFocusGained
        // TODO add your handling code here:
        txtTel.setBackground(Color.ORANGE);
    }//GEN-LAST:event_txtTelFocusGained

    private void txtvilledFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtvilledFocusGained
        // TODO add your handling code here:
        txtvilled.setBackground(Color.ORANGE);
    }//GEN-LAST:event_txtvilledFocusGained

    private void txtDateFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDateFocusGained
        // TODO add your handling code here:
        txtDate.setBackground(Color.ORANGE);
    }//GEN-LAST:event_txtDateFocusGained

    private void txtcoutFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtcoutFocusGained
        // TODO add your handling code here:
        txtcout.setBackground(Color.ORANGE);
    }//GEN-LAST:event_txtcoutFocusGained

    private void txttypeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txttypeFocusLost
        // TODO add your handling code here:
        txttype.setBackground(Color.white);
    }//GEN-LAST:event_txttypeFocusLost

    private void txtpoidFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtpoidFocusLost
        // TODO add your handling code here:
        txtpoid.setBackground(Color.white);
    }//GEN-LAST:event_txtpoidFocusLost

    private void txtnumFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnumFocusLost
        // TODO add your handling code here:
        txtnum.setBackground(Color.white);
    }//GEN-LAST:event_txtnumFocusLost

    private void txtnomFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnomFocusLost
        // TODO add your handling code here:
        txtnom.setBackground(Color.white);
    }//GEN-LAST:event_txtnomFocusLost

    private void txtprenomFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtprenomFocusLost
        // TODO add your handling code here:
        txtprenom.setBackground(Color.white);
    }//GEN-LAST:event_txtprenomFocusLost

    private void txttelFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txttelFocusLost
        // TODO add your handling code here:
        txttel.setBackground(Color.white);
    }//GEN-LAST:event_txttelFocusLost

    private void txtnumpFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnumpFocusLost
        // TODO add your handling code here:
        txtnump.setBackground(Color.white);
    }//GEN-LAST:event_txtnumpFocusLost

    private void txttpFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txttpFocusLost
        // TODO add your handling code here:
        txttp.setBackground(Color.white);
    }//GEN-LAST:event_txttpFocusLost

    private void txtvilleFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtvilleFocusLost
        // TODO add your handling code here:
        txtville.setBackground(Color.white);
    }//GEN-LAST:event_txtvilleFocusLost

    private void txtnomdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnomdFocusLost
        // TODO add your handling code here:
        txtnomd.setBackground(Color.white);
    }//GEN-LAST:event_txtnomdFocusLost

    private void txtprenomdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtprenomdFocusLost
        // TODO add your handling code here:
        txtprenomd.setBackground(Color.white);
    }//GEN-LAST:event_txtprenomdFocusLost

    private void txtTelFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTelFocusLost
        // TODO add your handling code here:
        txtTel.setBackground(Color.white);
    }//GEN-LAST:event_txtTelFocusLost

    private void txtvilledFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtvilledFocusLost
        // TODO add your handling code here:
        txtville.setBackground(Color.white);
    }//GEN-LAST:event_txtvilledFocusLost

    private void txtDateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDateFocusLost
        // TODO add your handling code here:
        txtDate.setBackground(Color.white);
    }//GEN-LAST:event_txtDateFocusLost

    private void txtcoutFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtcoutFocusLost
        // TODO add your handling code here:
        txtcout.setBackground(Color.white);
    }//GEN-LAST:event_txtcoutFocusLost

    private void txttypeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttypeKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            if(txttype.getText().trim().length()!=0)
            txtpoid.grabFocus();
            else{
                JOptionPane.showMessageDialog(null, "veuillez remplir le type");
                txttype.grabFocus();
            }
        }
    }//GEN-LAST:event_txttypeKeyPressed

    private void txtpoidKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpoidKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            if(txtpoid.getText().trim().length()!=0)
            txtnum.grabFocus();
            else{
                JOptionPane.showMessageDialog(null, "veuillez remplir le poids");
                txtpoid.grabFocus();
            }
        }
    }//GEN-LAST:event_txtpoidKeyPressed

    private void txtnumKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnumKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            if(txtnum.getText().trim().length()!=0)
            txtnom.grabFocus();
            else{
                JOptionPane.showMessageDialog(null, "veuillez remplir le numero_envoi");
                txtnum.grabFocus();
            }
        }
    }//GEN-LAST:event_txtnumKeyPressed

    private void txtnomKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnomKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            if(txtnom.getText().trim().length()!=0)
            txtprenom.grabFocus();
            else{
                JOptionPane.showMessageDialog(null, "veuillez remplir le nom");
                txtnom.grabFocus();
            }
        }
    }//GEN-LAST:event_txtnomKeyPressed

    private void txtprenomKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtprenomKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            if(txtprenom.getText().trim().length()!=0)
            txttel.grabFocus();
            else{
                JOptionPane.showMessageDialog(null, "veuillez remplir le prenom");
                txtprenom.grabFocus();
            }
        }
    }//GEN-LAST:event_txtprenomKeyPressed

    private void txttelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttelKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            if(txttel.getText().trim().length()!=0)
            txtnump.grabFocus();
            else{
                JOptionPane.showMessageDialog(null, "veuillez remplir le numero envoyeur");
                txttel.grabFocus();
            }
        }
    }//GEN-LAST:event_txttelKeyPressed

    private void txtnumpKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnumpKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            if(txtnump.getText().trim().length()!=0)
            txttp.grabFocus();
            else{
                JOptionPane.showMessageDialog(null, "veuillez remplir le numero_piece envoyeur");
                txtnump.grabFocus();
            }
        }
    }//GEN-LAST:event_txtnumpKeyPressed

    private void txttpKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttpKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            if(txttp.getText().trim().length()!=0)
            txtville.grabFocus();
            else{
                JOptionPane.showMessageDialog(null, "veuillez remplir le type de piece");
                txttp.grabFocus();
            }
        }
    }//GEN-LAST:event_txttpKeyPressed

    private void txtvilleKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtvilleKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            if(txtville.getText().trim().length()!=0)
            txtnomd.grabFocus();
            else{
                JOptionPane.showMessageDialog(null, "veuillez remplir la ville_Envoyeur");
                txtville.grabFocus();
            }
        }
    }//GEN-LAST:event_txtvilleKeyPressed

    private void txtnomdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnomdKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            if(txtnomd.getText().trim().length()!=0)
            txtprenomd.grabFocus();
            else{
                JOptionPane.showMessageDialog(null, "veuillez remplir le nom de destinataire");
                txtnomd.grabFocus();
            }
        }
    }//GEN-LAST:event_txtnomdKeyPressed

    private void txtprenomdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtprenomdKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            if(txtprenomd.getText().trim().length()!=0)
            txtTel.grabFocus();
            else{
                JOptionPane.showMessageDialog(null, "veuillez remplir le prenom de destinataire");
                txtprenomd.grabFocus();
            }
        }
    }//GEN-LAST:event_txtprenomdKeyPressed

    private void txtTelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            if(txtTel.getText().trim().length()!=0)
            txtvilled.grabFocus();
            else{
                JOptionPane.showMessageDialog(null, "veuillez remplir le numero de destinataire");
                txtTel.grabFocus();
            }
        }
    }//GEN-LAST:event_txtTelKeyPressed

    private void txtvilledKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtvilledKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            if(txtvilled.getText().trim().length()!=0)
            txtDate.grabFocus();
            else{
                JOptionPane.showMessageDialog(null, "veuillez remplir la ville de destinataire");
                txtvilled.grabFocus();
            }
        }
    }//GEN-LAST:event_txtvilledKeyPressed

    private void txtDateKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDateKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            if(txtDate.getText().trim().length()!=0)
            txtcout.grabFocus();
            else{
                JOptionPane.showMessageDialog(null, "veuillez remplir la date_envoi");
                txtDate.grabFocus();
            }
        }
    }//GEN-LAST:event_txtDateKeyPressed

    private void txtcoutKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcoutKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            if(txtcout.getText().trim().length()!=0)
            txttype.grabFocus();
            else{
                JOptionPane.showMessageDialog(null, "veuillez remplir le cout_envoi");
                txtcout.grabFocus();
            }
        }
    }//GEN-LAST:event_txtcoutKeyPressed

    private void btnlisteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnlisteMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnlisteMouseClicked

    private void btnlisteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlisteActionPerformed
        // TODO add your handling code here:
        Info InfoFrame = new Info();
              InfoFrame.setVisible(true);
              InfoFrame.pack();
              InfoFrame.setLocationRelativeTo(null); 
              this.dispose();
    }//GEN-LAST:event_btnlisteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Quitterbtn;
    private javax.swing.JButton btnliste;
    private javax.swing.JButton btnnouveau;
    private javax.swing.JButton btnvalider;
    private javax.swing.JPanel dpane;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtTel;
    private javax.swing.JTextField txtcout;
    private javax.swing.JTextField txtnom;
    private javax.swing.JTextField txtnomd;
    private javax.swing.JTextField txtnum;
    private javax.swing.JTextField txtnump;
    private javax.swing.JTextField txtpoid;
    private javax.swing.JTextField txtprenom;
    private javax.swing.JTextField txtprenomd;
    private javax.swing.JTextField txttel;
    private javax.swing.JTextField txttp;
    private javax.swing.JTextField txttype;
    private javax.swing.JTextField txtville;
    private javax.swing.JTextField txtvilled;
    // End of variables declaration//GEN-END:variables
}
