/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetjava;

import java.sql.*;
import classe.GestionColis;
import projetjava.Infor;
import classe.connexionbd;
import classe.exportercolis;
import com.sun.glass.events.KeyEvent;
import java.awt.Color;
import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class Reception extends javax.swing.JFrame {
public static Connection c, ce;
    public static Statement st, ste;
    public static ResultSet rs, rse;
    public static PreparedStatement ps, pse;
    /**
     * Creates new form Reception
     */
    public Reception() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        dpaner = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtnomr = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txttelr = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtnumpr = new javax.swing.JTextField();
        txtprenomr = new javax.swing.JTextField();
        txtnumr = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txttyper = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtdater = new javax.swing.JTextField();
        btnnouveaur = new javax.swing.JButton();
        btnvaliderr = new javax.swing.JButton();
        Quitterbtnr = new javax.swing.JButton();
        btnlister = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtnenr = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtpenr = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setFont(new java.awt.Font("SimSun-ExtB", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Reception colis");

        dpaner.setBackground(new java.awt.Color(0, 102, 102));
        dpaner.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setFont(new java.awt.Font("SimSun-ExtB", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("NumeroEnvoi");

        jLabel3.setFont(new java.awt.Font("SimSun-ExtB", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("NomRecepteur");

        txtnomr.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtnomr.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtnomrFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtnomrFocusLost(evt);
            }
        });
        txtnomr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnomrActionPerformed(evt);
            }
        });
        txtnomr.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnomrKeyPressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("SimSun-ExtB", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("PrenomRecepteur");

        jLabel5.setFont(new java.awt.Font("SimSun-ExtB", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("TelRecepteur");

        txttelr.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txttelr.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txttelrFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txttelrFocusLost(evt);
            }
        });
        txttelr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttelrActionPerformed(evt);
            }
        });
        txttelr.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txttelrKeyPressed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("SimSun-ExtB", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("NumeropieceR");

        txtnumpr.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtnumpr.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtnumprFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtnumprFocusLost(evt);
            }
        });
        txtnumpr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnumprActionPerformed(evt);
            }
        });
        txtnumpr.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnumprKeyPressed(evt);
            }
        });

        txtprenomr.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtprenomr.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtprenomrFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtprenomrFocusLost(evt);
            }
        });
        txtprenomr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtprenomrActionPerformed(evt);
            }
        });
        txtprenomr.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtprenomrKeyPressed(evt);
            }
        });

        txtnumr.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtnumr.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtnumrFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtnumrFocusLost(evt);
            }
        });
        txtnumr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnumrActionPerformed(evt);
            }
        });
        txtnumr.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnumrKeyPressed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("SimSun-ExtB", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Type_piece");

        txttyper.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txttyper.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txttyperFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txttyperFocusLost(evt);
            }
        });
        txttyper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttyperActionPerformed(evt);
            }
        });
        txttyper.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txttyperKeyPressed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("SimSun-ExtB", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Date de reception");

        txtdater.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtdater.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtdaterFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtdaterFocusLost(evt);
            }
        });
        txtdater.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdaterActionPerformed(evt);
            }
        });
        txtdater.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtdaterKeyPressed(evt);
            }
        });

        btnnouveaur.setBackground(new java.awt.Color(255, 255, 255));
        btnnouveaur.setFont(new java.awt.Font("SimSun-ExtB", 1, 24)); // NOI18N
        btnnouveaur.setText("Nouveau");
        btnnouveaur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnouveaurActionPerformed(evt);
            }
        });

        btnvaliderr.setBackground(new java.awt.Color(255, 255, 255));
        btnvaliderr.setFont(new java.awt.Font("SimSun-ExtB", 1, 24)); // NOI18N
        btnvaliderr.setText("VALIDER");
        btnvaliderr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvaliderrActionPerformed(evt);
            }
        });

        Quitterbtnr.setBackground(new java.awt.Color(255, 255, 255));
        Quitterbtnr.setFont(new java.awt.Font("SimSun-ExtB", 1, 24)); // NOI18N
        Quitterbtnr.setText("Quitter");
        Quitterbtnr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                QuitterbtnrMouseClicked(evt);
            }
        });
        Quitterbtnr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuitterbtnrActionPerformed(evt);
            }
        });

        btnlister.setBackground(new java.awt.Color(255, 255, 255));
        btnlister.setFont(new java.awt.Font("SimSun-ExtB", 1, 24)); // NOI18N
        btnlister.setText("Liste Reception");
        btnlister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnlisterMouseClicked(evt);
            }
        });
        btnlister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlisterActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("SimSun-ExtB", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Nom Envoyeur");

        txtnenr.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtnenr.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtnenrFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtnenrFocusLost(evt);
            }
        });
        txtnenr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnenrActionPerformed(evt);
            }
        });
        txtnenr.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnenrKeyPressed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("SimSun-ExtB", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Prenom Envoyeur");

        txtpenr.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtpenr.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtpenrFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtpenrFocusLost(evt);
            }
        });
        txtpenr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpenrActionPerformed(evt);
            }
        });
        txtpenr.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtpenrKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout dpanerLayout = new javax.swing.GroupLayout(dpaner);
        dpaner.setLayout(dpanerLayout);
        dpanerLayout.setHorizontalGroup(
            dpanerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dpanerLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(dpanerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4)
                    .addComponent(txtprenomr, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(txtnumr, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                    .addComponent(txtnomr))
                .addGap(169, 169, 169)
                .addGroup(dpanerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dpanerLayout.createSequentialGroup()
                        .addGroup(dpanerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(dpanerLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(txtpenr, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, dpanerLayout.createSequentialGroup()
                                .addGroup(dpanerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtnumpr, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
                                    .addComponent(txttyper))
                                .addGap(118, 118, 118)
                                .addGroup(dpanerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtnenr)
                                    .addComponent(txtdater)
                                    .addGroup(dpanerLayout.createSequentialGroup()
                                        .addGroup(dpanerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel9))
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addGap(220, 220, 220))
                    .addGroup(dpanerLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(305, 305, 305))
                    .addGroup(dpanerLayout.createSequentialGroup()
                        .addGroup(dpanerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(txttelr, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(72, 575, Short.MAX_VALUE))))
            .addGroup(dpanerLayout.createSequentialGroup()
                .addGap(299, 299, 299)
                .addGroup(dpanerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnnouveaur, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                    .addComponent(Quitterbtnr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(273, 273, 273)
                .addGroup(dpanerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnvaliderr, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnlister))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dpanerLayout.setVerticalGroup(
            dpanerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dpanerLayout.createSequentialGroup()
                .addGroup(dpanerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dpanerLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtnumr, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dpanerLayout.createSequentialGroup()
                        .addGroup(dpanerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(dpanerLayout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dpanerLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(dpanerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dpanerLayout.createSequentialGroup()
                                .addComponent(txttelr, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dpanerLayout.createSequentialGroup()
                                .addComponent(txtdater, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7)))))
                .addGroup(dpanerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dpanerLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(dpanerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtnomr, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                            .addComponent(txtnumpr))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dpanerLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(txtnenr, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(dpanerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dpanerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtprenomr, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(dpanerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txttyper, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtpenr, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(51, 51, 51)
                .addGroup(dpanerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnvaliderr, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnnouveaur, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(dpanerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnlister, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Quitterbtnr, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(693, 693, 693)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(dpaner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(dpaner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(486, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnomrFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnomrFocusGained
        // TODO add your handling code here:
        txtnomr.setBackground(Color.ORANGE);
    }//GEN-LAST:event_txtnomrFocusGained

    private void txtnomrFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnomrFocusLost
        // TODO add your handling code here:
        txtnomr.setBackground(Color.white);
    }//GEN-LAST:event_txtnomrFocusLost

    private void txtnomrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnomrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnomrActionPerformed

    private void txtnomrKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnomrKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            if(txtnomr.getText().trim().length()!=0)
            txtprenomr.grabFocus();
            else{
                JOptionPane.showMessageDialog(null, "veuillez remplir le nom");
                txtnomr.grabFocus();
            }
        }
    }//GEN-LAST:event_txtnomrKeyPressed

    private void txttelrFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txttelrFocusGained
        // TODO add your handling code here:
        txttelr.setBackground(Color.ORANGE);
    }//GEN-LAST:event_txttelrFocusGained

    private void txttelrFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txttelrFocusLost
        // TODO add your handling code here:
        txttelr.setBackground(Color.white);
    }//GEN-LAST:event_txttelrFocusLost

    private void txttelrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttelrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttelrActionPerformed

    private void txttelrKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttelrKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            if(txttelr.getText().trim().length()!=0)
            txtnumpr.grabFocus();
            else{
                JOptionPane.showMessageDialog(null, "veuillez remplir le numero de telephone");
                txttelr.grabFocus();
            }
        }
    }//GEN-LAST:event_txttelrKeyPressed

    private void txtnumprFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnumprFocusGained
        // TODO add your handling code here:
        txtnumpr.setBackground(Color.ORANGE);
    }//GEN-LAST:event_txtnumprFocusGained

    private void txtnumprFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnumprFocusLost
        // TODO add your handling code here:
        txtnumpr.setBackground(Color.white);
    }//GEN-LAST:event_txtnumprFocusLost

    private void txtnumprActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnumprActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnumprActionPerformed

    private void txtnumprKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnumprKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            if(txtnumpr.getText().trim().length()!=0)
            txttyper.grabFocus();
            else{
                JOptionPane.showMessageDialog(null, "veuillez remplir le numero de piece ");
                txtnumpr.grabFocus();
            }
        }
    }//GEN-LAST:event_txtnumprKeyPressed

    private void txtprenomrFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtprenomrFocusGained
        // TODO add your handling code here:
        txtprenomr.setBackground(Color.ORANGE);
    }//GEN-LAST:event_txtprenomrFocusGained

    private void txtprenomrFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtprenomrFocusLost
        // TODO add your handling code here:
        txtprenomr.setBackground(Color.white);
    }//GEN-LAST:event_txtprenomrFocusLost

    private void txtprenomrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtprenomrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtprenomrActionPerformed

    private void txtprenomrKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtprenomrKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            if(txtprenomr.getText().trim().length()!=0)
            txttelr.grabFocus();
            else{
                JOptionPane.showMessageDialog(null, "veuillez remplir le prenom");
                txtprenomr.grabFocus();
            }
        }
    }//GEN-LAST:event_txtprenomrKeyPressed

    private void txtnumrFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnumrFocusGained
        // TODO add your handling code here:
        txtnumr.setBackground(Color.ORANGE);
    }//GEN-LAST:event_txtnumrFocusGained

    private void txtnumrFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnumrFocusLost
        // TODO add your handling code here:
        txtnumr.setBackground(Color.white);
    }//GEN-LAST:event_txtnumrFocusLost

    private void txtnumrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnumrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnumrActionPerformed

    private void txtnumrKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnumrKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            if(txtnumr.getText().trim().length()!=0)
            txtnomr.grabFocus();
            else{
                JOptionPane.showMessageDialog(null, "veuillez remplir le numero de l'envoi");
                txtnumr.grabFocus();
            }
        }
    }//GEN-LAST:event_txtnumrKeyPressed

    private void txttyperFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txttyperFocusGained
        // TODO add your handling code here:
        txttyper.setBackground(Color.ORANGE);
    }//GEN-LAST:event_txttyperFocusGained

    private void txttyperFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txttyperFocusLost
        // TODO add your handling code here:
        txttyper.setBackground(Color.white);
    }//GEN-LAST:event_txttyperFocusLost

    private void txttyperActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttyperActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttyperActionPerformed

    private void txttyperKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttyperKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            if(txttyper.getText().trim().length()!=0)
            txtdater.grabFocus();
            else{
                JOptionPane.showMessageDialog(null, "veuillez remplir le type de piece");
                txttyper.grabFocus();
            }
        }
    }//GEN-LAST:event_txttyperKeyPressed

    private void txtdaterFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtdaterFocusGained
        // TODO add your handling code here:
        txtdater.setBackground(Color.ORANGE);
    }//GEN-LAST:event_txtdaterFocusGained

    private void txtdaterFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtdaterFocusLost
        // TODO add your handling code here:
        txtdater.setBackground(Color.white);
    }//GEN-LAST:event_txtdaterFocusLost

    private void txtdaterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdaterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdaterActionPerformed

    private void txtdaterKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdaterKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            if(txtdater.getText().trim().length()!=0)
            txtnumr.grabFocus();
            else{
                JOptionPane.showMessageDialog(null, "veuillez remplir le numero_piece envoyeur");
                txtdater.grabFocus();
            }
        }
    }//GEN-LAST:event_txtdaterKeyPressed

    private void btnnouveaurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnouveaurActionPerformed
        // TODO add your handling code here:
        txtnumr.setEnabled(true);
        txtnomr.setEnabled(true);
        txtprenomr.setEnabled(true);
        txttelr.setEnabled(true);
        txtnumpr.setEnabled(true);
        txttyper.setEnabled(true);
        txtdater.setEnabled(true);
         txtnenr.setEnabled(true);
          txtpenr.setEnabled(true);
        btnnouveaur.setEnabled(false);
        btnvaliderr.setEnabled(true);
        txtnumr.grabFocus();
    }//GEN-LAST:event_btnnouveaurActionPerformed

    private void btnvaliderrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvaliderrActionPerformed
        // TODO add your handling code here:
        String numero_envoie=txtnumr.getText(),nom_recepteur=txtnomr.getText(),prenom_recepteur=txtprenomr.getText(),telephone_recepteur=txttelr.getText(),numero_piece_recepteur=txtnumpr.getText(),type_piece_recepteur=txttyper.getText(),
                date_reception=txtdater.getText(),nomEr=txtnenr.getText(),prenomEr=txtpenr.getText();
       
        GestionColis.enregistrerReception(numero_envoie,nom_recepteur,prenom_recepteur,telephone_recepteur,numero_piece_recepteur,type_piece_recepteur, date_reception,nomEr,prenomEr);
        
        
        txtnumr.setText("");
        txtnomr.setText("");
        txtprenomr.setText("");
         txttelr.setText("");
        txtnumpr.setText("");
        txttyper.setText("");
         txtdater.setText("");
          txtnenr.setText("");
           txtpenr.setText("");
        txtnumr.setEnabled(false);
        txtnomr.setEnabled(false);
        txtprenomr.setEnabled(false);
        txttelr.setEnabled(false);
        txtnumpr.setEnabled(false);
        txttyper.setEnabled(false);
        txtdater.setEnabled(false);
        txtnenr.setEnabled(false);
        txtpenr.setEnabled(false);
        try {
    Connection con = connexionbd.seconnecter();
    Statement st = con.createStatement();
    ResultSet rs = st.executeQuery("SELECT * FROM colis WHERE numero_envoi='" + numero_envoie + "' AND nomE='" + nomEr + "' AND prenomE='" + prenomEr + "'");

    if (rs.next()) {
        Infor InforFrame = new Infor();
        InforFrame.setUser(numero_envoie); // Pass the user name to setUser method
        InforFrame.setVisible(true);
        InforFrame.pack();
        InforFrame.setLocationRelativeTo(null); 
        this.dispose();
    } else {
        JOptionPane.showMessageDialog(new JFrame(), "Incorrect numéro d'envoi, nom ou prénom", "Error", JOptionPane.ERROR_MESSAGE);
    }
} catch (SQLException e) {
    JOptionPane.showMessageDialog(new JFrame(), "Erreur SQL : " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
} catch (Exception e) {
    JOptionPane.showMessageDialog(new JFrame(), "Erreur de vérification : " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
}
      
    }//GEN-LAST:event_btnvaliderrActionPerformed

    private void QuitterbtnrMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QuitterbtnrMouseClicked
        // TODO add your handling code here:
        dpaner.removeAll();
        dpaner.repaint();
        //        appel jinternal frame
        Menu fg=new Menu();
        dpaner.add(fg);
        fg.setVisible(true);

    }//GEN-LAST:event_QuitterbtnrMouseClicked

    private void QuitterbtnrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuitterbtnrActionPerformed
        // TODO add your handling code here:
        Home HomeFrame = new Home();
        HomeFrame.setVisible(true);
        HomeFrame.pack();
        HomeFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_QuitterbtnrActionPerformed

    private void btnlisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnlisterMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnlisterMouseClicked

    private void btnlisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlisterActionPerformed
        // TODO add your handling code here:
        Infor InforFrame = new Infor();
        InforFrame.setVisible(true);
        InforFrame.pack();
        InforFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnlisterActionPerformed

    private void txtnenrFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnenrFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnenrFocusGained

    private void txtnenrFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnenrFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnenrFocusLost

    private void txtnenrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnenrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnenrActionPerformed

    private void txtnenrKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnenrKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnenrKeyPressed

    private void txtpenrFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtpenrFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpenrFocusGained

    private void txtpenrFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtpenrFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpenrFocusLost

    private void txtpenrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpenrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpenrActionPerformed

    private void txtpenrKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpenrKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpenrKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reception.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reception.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reception.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reception.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reception().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Quitterbtnr;
    private javax.swing.JButton btnlister;
    private javax.swing.JButton btnnouveaur;
    private javax.swing.JButton btnvaliderr;
    private javax.swing.JPanel dpaner;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtdater;
    private javax.swing.JTextField txtnenr;
    private javax.swing.JTextField txtnomr;
    private javax.swing.JTextField txtnumpr;
    private javax.swing.JTextField txtnumr;
    private javax.swing.JTextField txtpenr;
    private javax.swing.JTextField txtprenomr;
    private javax.swing.JTextField txttelr;
    private javax.swing.JTextField txttyper;
    // End of variables declaration//GEN-END:variables
}
