/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetjava;
import com.mysql.jdbc.Connection;
import java.awt.HeadlessException;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showMessageDialog;

/**
 *
 * @author HP
 */
public class SignUpr extends javax.swing.JFrame {

    /**
     * Creates new form SignUpr
     */
    public SignUpr() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelr = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        fnamer = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        roleur = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        passr = new javax.swing.JPasswordField();
        SignUpBtnr = new javax.swing.JButton();
        jButton1r = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel2r = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelr.setBackground(new java.awt.Color(255, 255, 255));
        jPanelr.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setBackground(new java.awt.Color(0, 102, 102));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setText("SIGN UP");
        jPanelr.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        jLabel5.setBackground(new java.awt.Color(102, 102, 102));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Full name");
        jPanelr.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        fnamer.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        fnamer.setForeground(new java.awt.Color(102, 102, 102));
        jPanelr.add(fnamer, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 332, 40));

        jLabel6.setBackground(new java.awt.Color(102, 102, 102));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Prenom");
        jPanelr.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        roleur.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        roleur.setForeground(new java.awt.Color(102, 102, 102));
        roleur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roleurActionPerformed(evt);
            }
        });
        jPanelr.add(roleur, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 332, 40));

        jLabel7.setBackground(new java.awt.Color(102, 102, 102));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Password");
        jPanelr.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));

        passr.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        passr.setForeground(new java.awt.Color(102, 102, 102));
        passr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passrActionPerformed(evt);
            }
        });
        jPanelr.add(passr, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 332, 40));

        SignUpBtnr.setBackground(new java.awt.Color(0, 102, 102));
        SignUpBtnr.setForeground(new java.awt.Color(51, 0, 0));
        SignUpBtnr.setText("Sign Up");
        SignUpBtnr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUpBtnrActionPerformed(evt);
            }
        });
        jPanelr.add(SignUpBtnr, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 380, 91, 37));

        jButton1r.setText("Retour");
        jButton1r.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1rActionPerformed(evt);
            }
        });
        jPanelr.add(jButton1r, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 480, 110, 40));

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\THIERRY\\Desktop\\Projet MOBILE\\TEMPLATE\\01\\PJAVA\\src\\Icon\\Facteur.png")); // NOI18N
        jPanelr.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 560, 550));

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\THIERRY\\Desktop\\Projet MOBILE\\TEMPLATE\\01\\PJAVA\\src\\Icon\\Garantia de Procedência.png")); // NOI18N
        jPanelr.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 670, 580));

        jLabel11.setText("jLabel11");
        jPanelr.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, -1, -1));

        jPanel2r.setBackground(new java.awt.Color(0, 102, 102));

        jLabel2.setFont(new java.awt.Font("Showcard Gothic", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Gestion colis");

        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("copyright © company name All rights reserved");

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\THIERRY\\Desktop\\Projet MOBILE\\TEMPLATE\\01\\PJAVA\\src\\Icon\\logo_1.png")); // NOI18N

        javax.swing.GroupLayout jPanel2rLayout = new javax.swing.GroupLayout(jPanel2r);
        jPanel2r.setLayout(jPanel2rLayout);
        jPanel2rLayout.setHorizontalGroup(
            jPanel2rLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2rLayout.createSequentialGroup()
                .addGroup(jPanel2rLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2rLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jLabel3))
                    .addGroup(jPanel2rLayout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addGroup(jPanel2rLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel1)))
                    .addGroup(jPanel2rLayout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(jLabel2)))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jPanel2rLayout.setVerticalGroup(
            jPanel2rLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2rLayout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(69, 69, 69)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(64, 64, 64))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2r, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelr, javax.swing.GroupLayout.PREFERRED_SIZE, 659, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelr, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2r, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SignUpBtnrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUpBtnrActionPerformed
        //System.out.println("Sign up btn clicked");
        //System.out.println("Sign up btn clicked");
        String nom_responsable, prenom_responsable, mot_de_passer, queryr;
        String SUrlr, SUserr, SPassr;
        SUrlr = "jdbc:mysql://localhost:3306/colis"; // Note: MySQL should be in lowercase.
        SUserr = "root";
        SPassr = "";

        try {
            Class.forName("com.mysql.jdbc.Driver"); // Updated driver class name for MySQL Connector/J 8.0+
            Connection con = (Connection) DriverManager.getConnection(SUrlr, SUserr, SPassr);
            Statement st = con.createStatement();

            if ("".equals(fnamer.getText())) {
                JOptionPane.showMessageDialog(new JFrame(), "Full Name is required", "Error", JOptionPane.ERROR_MESSAGE);
            } else if ("".equals(roleur.getText())) {
                JOptionPane.showMessageDialog(new JFrame(), "Prenom Name is required", "Error", JOptionPane.ERROR_MESSAGE);
            } else if ("".equals(passr.getText())) {
                JOptionPane.showMessageDialog(new JFrame(), "Password is required", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                nom_responsable = fnamer.getText();
                prenom_responsable = roleur.getText();
                mot_de_passer = new String(passr.getPassword()); // Correct way to get password text

                queryr = "INSERT INTO responsable (nom_responsable, prenom_responsable, mot_de_passer) VALUES ('" + nom_responsable + "', '" + prenom_responsable + "', '" + mot_de_passer + "')";

                st.executeUpdate(queryr);

                fnamer.setText("");
                roleur.setText("");
                passr.setText("");

                JOptionPane.showMessageDialog(null, "New Account has been created successfully!");
            }
        } catch (ClassNotFoundException | SQLException | HeadlessException e) {
            System.out.println("Error! " + e.getMessage());
        }
    }//GEN-LAST:event_SignUpBtnrActionPerformed

    private void jButton1rActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1rActionPerformed
        // TODO add your handling code here:
         Homer HomerFrame = new Homer();
        HomerFrame.setVisible(true);
        HomerFrame.pack();
        HomerFrame.setLocationRelativeTo(null); 
        this.dispose();
    }//GEN-LAST:event_jButton1rActionPerformed

    private void passrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passrActionPerformed

    private void roleurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roleurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roleurActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUpr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUpr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUpr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUpr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUpr().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SignUpBtnr;
    private javax.swing.JTextField fnamer;
    private javax.swing.JButton jButton1r;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2r;
    private javax.swing.JPanel jPanelr;
    private javax.swing.JPasswordField passr;
    private javax.swing.JTextField roleur;
    // End of variables declaration//GEN-END:variables
}
